config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :invitations => 'users/invitations' }

  devise_scope :user do
    authenticated :user do
      root 'main#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root to: 'main#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  attr_accessor :skip_generate_invitation_token

  def can_resend_invite_to?(user)
    return true if user.invitation_sent_at.nil?
    (Date.today.to_date - user.invitation_sent_at.to_date).to_i > Devise.resend_invitation_during_days
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  private

  def invite_resource
    resource_class.invite!(invite_params, current_inviter) do |u|
      unless current_inviter.can_resend_invite_to?(u)
        u.errors.add(:email, :excess_of_resend_invitation_during_days,
                     { email: u.email, days: Devise.resend_invitation_during_days })
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title PrettyKitty
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if flash[:notice]
      .notice= flash[:notice]
    = yield

app/views/main/index.html.haml
= image_tag 'Pretty-Kitty', height: 300
= link_to t('invite_friend'), new_user_invitation_path

= link_to t('logout'), destroy_user_session_path, method: :delete